version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      tree-sitter:
        patterns:
          - "github.com/tree-sitter/*"
      golang-x:
        patterns:
          - "golang.org/*"

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
