/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** API and Trace binary versions */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/project": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bound project root, store readiness, safe UI flags */
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tasks (mirrors `trace tasks` / `trace_tasks`) */
        get: operations["listTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one task by id */
        get: operations["getTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/loop/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Loop status for a seed task (mirrors `trace_loop` action=status) */
        get: operations["getLoopStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/loop/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Build next-work packet (mirrors `trace_loop` action=next) */
        get: operations["getLoopNext"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/loop/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply loop envelope `trace.loop.apply.v1` (mirrors `trace_loop` action=apply) */
        post: operations["postLoopApply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/loop/gate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Deliberation gate check (mirrors `trace loop gate`)
         * @description CLI-parity gate (`trace.loop.gate.v1`). MCP `trace_loop` does not expose gate;
         *     HTTP includes it because the library/CLI surface exists and the GUI loop console needs it.
         */
        get: operations["getLoopGate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/loop/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset deliberation / saturation state (mirrors `trace loop reset`)
         * @description CLI-parity reset. MCP does not expose reset; HTTP includes it for GUI loop console.
         */
        post: operations["postLoopReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create entity (`trace add` / `trace_add` parity) */
        post: operations["createEntity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entities/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get entity by id */
        get: operations["getEntity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create relation (`trace link` / `trace_link` parity) */
        post: operations["createLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply work_state transition (`trace transition` / `trace_transition` parity) */
        post: operations["createTransition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bounded context packet (mirrors `trace context` / `trace_context`) */
        get: operations["getContext"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/why": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bounded why packet (mirrors `trace why` / `trace_why`) */
        get: operations["getWhy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search query (mirrors `trace search` / `trace_search`) */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/seed/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Seed export/import readiness summary (not a full graph body) */
        get: operations["getSeedStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/seed/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start or request seed export job; returns status/summary — not default full-graph body
         * @description HTTP must not return an unbounded full-graph document as the default success body.
         *     Prefer job status + path/size/summary fields; file write remains a local/CLI concern unless
         *     a future bounded artifact download is explicitly designed.
         */
        post: operations["postSeedExport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/seed/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start or request seed import; returns status/summary */
        post: operations["postSeedImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Budgeted subgraph / neighborhood (never full dump)
         * @description Requires explicit `max_nodes` and a center entity id. Servers MUST reject
         *     unbounded requests. Default full-graph export is forbidden.
         */
        get: operations["getGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List reviews */
        get: operations["listReviews"];
        put?: never;
        /** Create review (`trace review` create) */
        post: operations["createReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews/{review_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get review */
        get: operations["getReview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plan tree / plan listing (separate from budgeted graph) */
        get: operations["listPlans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/capability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capability list / decisions */
        get: operations["listCapability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/impact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Impact report */
        get: operations["getImpact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Change listing */
        get: operations["listChanges"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/regressions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Regression listing */
        get: operations["listRegressions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List / recommend agents */
        get: operations["listAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Index status */
        get: operations["getIndexStatus"];
        put?: never;
        /** Trigger reindex (ops) */
        post: operations["postIndexReindex"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue or rotate local serve bearer token (non-loopback / optional) */
        post: operations["postAuthToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Backup (deferred — CLI-first) */
        post: operations["postBackup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore (deferred — CLI-first) */
        post: operations["postRestore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/migrate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Migrate (deferred — CLI-first) */
        post: operations["postMigrate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/install": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Install harness hooks (deferred — CLI-first) */
        post: operations["postInstall"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/patterns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Patterns browse (deferred) */
        get: operations["listPatterns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/knowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Knowledge deep browse (deferred) */
        get: operations["listKnowledge"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/eval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Eval / outcomes (deferred) */
        get: operations["getEval"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * SSE / push event stream (deferred product feature)
         * @description Not in Phase 29 MVP. Reserved path only.
         */
        get: operations["getEventsSSE"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorEnvelope: {
            error: {
                /** @description Machine-readable code (e.g. VALIDATION_ERROR) */
                code: string;
                message: string;
                /** @description Optional structured context */
                details?: unknown;
            };
        };
        HealthResponse: {
            /** @constant */
            ok: true;
        };
        VersionResponse: {
            ok: boolean;
            /** @example trace */
            name: string;
            /**
             * @description HTTP contract version
             * @example 1.0.0
             */
            api_version: string;
            /** @description Trace binary / build version */
            trace_version: string;
        };
        ProjectResponse: {
            /** @description Absolute project root */
            root: string;
            /** @description Path to `.trace/` (may be omitted if sensitive in remote mode) */
            store_path?: string;
            store_ready: boolean;
            /** @description Safe UI feature flags only */
            flags?: {
                [key: string]: unknown;
            };
        };
        TaskRow: {
            /** Format: uuid */
            id: string;
            title: string;
            work_state: string;
            /** Format: uuid */
            goal_id?: string | null;
            body?: string | null;
        };
        TaskListResponse: {
            items: components["schemas"]["TaskRow"][];
            next_cursor?: string | null;
        };
        EntitySummary: {
            /** Format: uuid */
            id: string;
            /** @description goal|task|decision|assumption|discovery|plan-change|claim|evidence|… */
            kind: string;
            title: string;
            body?: string | null;
            work_state?: string | null;
        };
        CreateEntityRequest: {
            kind: string;
            title: string;
            body?: string;
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            goal_id?: string;
            source_type?: string;
            confidence?: number;
            status?: string;
        };
        CreateLinkRequest: {
            rel: string;
            /** Format: uuid */
            from: string;
            /** Format: uuid */
            to: string;
            source_type?: string;
        };
        LinkSummary: {
            rel: string;
            /** Format: uuid */
            from: string;
            /** Format: uuid */
            to: string;
        };
        CreateTransitionRequest: {
            /** Format: uuid */
            task_id: string;
            to_state: string;
            reason: string;
            /** @description Provenance label only — not authorization */
            actor?: string;
            allow_done?: boolean;
            as_operator?: boolean;
            allow_missing_caps?: boolean;
            evidence_ids?: string[];
        };
        TransitionResult: {
            /** Format: uuid */
            task_id: string;
            work_state: string;
            warning?: string | null;
        };
        /** @description Schema TODO — map 1:1 from loop.Status library JSON in S03 */
        LoopStatusResponse: {
            [key: string]: unknown;
        };
        /** @description Schema TODO — map 1:1 from loop.BuildNextPacket JSON in S03 */
        LoopNextResponse: {
            [key: string]: unknown;
        };
        /** @description Align field names to loop.ApplyEnvelope in S03; do not invent silent forks */
        LoopApplyEnvelope: {
            /** @description Expected trace.loop.apply.v1 */
            schema_version: string;
            /** Format: uuid */
            apply_id: string;
            seed: {
                /** Format: uuid */
                task_id: string;
                /** Format: uuid */
                goal_id?: string;
            };
            writes?: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /** @description Schema TODO — map from loop.Apply result in S03 */
        LoopApplyResult: {
            [key: string]: unknown;
        };
        /** @description Schema TODO — map 1:1 from trace.loop.gate.v1 / loop.EvaluateGate in S03 */
        LoopGateResponse: {
            [key: string]: unknown;
        };
        /** @description Schema TODO — map from deliberation reset result in S03 */
        LoopResetResponse: {
            [key: string]: unknown;
        };
        /** @description Bounded packet; depth/format params constrain size (Law 7) */
        ContextPacket: {
            [key: string]: unknown;
        };
        /** @description Bounded causal neighborhood (Law 6–7) */
        WhyPacket: {
            [key: string]: unknown;
        };
        SearchResponse: {
            items: {
                /** Format: uuid */
                id: string;
                kind: string;
                title: string;
                snippet?: string | null;
            }[];
        };
        /** @description Summary only — not a graph dump */
        SeedStatus: {
            ready: boolean;
            /** Format: date-time */
            last_export_at?: string | null;
            /** Format: date-time */
            last_import_at?: string | null;
            notes?: string | null;
        };
        SeedExportRequest: {
            /**
             * @description Optional local path hint for CLI-parity export. Must resolve under the
             *     bound project root (or an explicit allowlisted export dir). Absolute
             *     paths outside the project MUST be rejected — especially under `--allow-remote`.
             */
            output_path?: string;
            strict?: boolean;
            /** Format: uuid */
            task_id?: string;
        };
        SeedImportRequest: {
            /**
             * @description Local path to seed JSON (server-local filesystem). Must resolve under
             *     the bound project root; path traversal / escape MUST be rejected.
             *     Prefer project-relative paths in clients.
             */
            input_path: string;
        };
        /** @description Status/summary — must not embed full seed document by default */
        SeedJobStatus: {
            /** @enum {string} */
            status: "ok" | "pending" | "failed";
            summary?: string | null;
            path?: string | null;
            entity_count?: number | null;
            link_count?: number | null;
            error?: string | null;
        };
        GraphNode: {
            /** Format: uuid */
            id: string;
            kind: string;
            title: string;
        };
        GraphEdge: {
            rel: string;
            /** Format: uuid */
            from: string;
            /** Format: uuid */
            to: string;
        };
        BoundedGraph: {
            /** @enum {string} */
            mode?: "project";
            /** Format: uuid */
            center: string;
            max_nodes: number;
            /** @description Total project entities before truncation (mode=project only) */
            total_entities?: number;
            nodes: components["schemas"]["GraphNode"][];
            edges: components["schemas"]["GraphEdge"][];
            /** @description True if neighborhood or project graph exceeded budget */
            truncated: boolean;
        };
        ReviewSummary: {
            /** Format: uuid */
            id: string;
            title: string;
            body?: string | null;
            /** @enum {string|null} */
            result?: "PASS" | "FAIL" | "UNCERTAIN" | null;
            /** Format: uuid */
            task_id?: string | null;
        };
    };
    responses: {
        /** @description Error envelope */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        TaskIdPath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version identity */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project meta */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listTasks: {
        parameters: {
            query?: {
                /** @description Optional goal UUID filter */
                goal_id?: string;
                /** @description Optional work_state filter */
                work_state?: string;
                /** @description Opaque pagination cursor (optional; S03 may start unpaginated) */
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskListResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: components["parameters"]["TaskIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRow"];
                };
            };
            404: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    getLoopStatus: {
        parameters: {
            query: {
                task_id: string;
                /** @description Optional; derived from task when omitted */
                goal_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Loop status payload (library-shaped; schema TODO align S03) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoopStatusResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getLoopNext: {
        parameters: {
            query: {
                task_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Next packet (bounded; library-shaped) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoopNextResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    postLoopApply: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoopApplyEnvelope"];
            };
        };
        responses: {
            /** @description Apply result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoopApplyResult"];
                };
            };
            409: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    getLoopGate: {
        parameters: {
            query: {
                task_id: string;
                /** @description Gate context (CLI `--for`) */
                for?: "orient" | "edit" | "execute" | "done" | "export";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Gate envelope (allowed + violations; schema TODO align S03) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoopGateResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    postLoopReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    task_id: string;
                };
            };
        };
        responses: {
            /** @description Post-reset deliberation state (schema TODO align S03) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoopResetResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createEntity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEntityRequest"];
            };
        };
        responses: {
            /** @description Created entity summary */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntitySummary"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getEntity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entity summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntitySummary"];
                };
            };
            404: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    createLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLinkRequest"];
            };
        };
        responses: {
            /** @description Created link */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkSummary"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createTransition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransitionRequest"];
            };
        };
        responses: {
            /** @description Transition applied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransitionResult"];
                };
            };
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    getContext: {
        parameters: {
            query: {
                task_id: string;
                /** @description 1=TaskContext 2=ExpandContext; max 2 */
                depth?: 1 | 2;
                format?: "json" | "markdown" | "both";
                include_why?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded context packet */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextPacket"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getWhy: {
        parameters: {
            query: {
                entity_type: string;
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded causal neighborhood */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhyPacket"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    search: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search hits */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSeedStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Seed status / summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeedStatus"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    postSeedExport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SeedExportRequest"];
            };
        };
        responses: {
            /** @description Export status / summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeedJobStatus"];
                };
            };
            /** @description Export accepted (async) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeedJobStatus"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    postSeedImport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeedImportRequest"];
            };
        };
        responses: {
            /** @description Import status / summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeedJobStatus"];
                };
            };
            /** @description Import accepted (async) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeedJobStatus"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getGraph: {
        parameters: {
            query: {
                /** @description When `project`, returns all entities (bounded by max_nodes) with edges between them */
                mode?: "project";
                /** @description Center entity id (required unless mode=project) */
                center?: string;
                /** @description Hard node budget (required; no implicit unlimited) */
                max_nodes: number;
                /** @description Hop depth for neighborhood mode only */
                depth?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Budgeted nodes and edges */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedGraph"];
                };
            };
            400: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    listReviews: {
        parameters: {
            query?: {
                task_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Review list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ReviewSummary"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createReview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title: string;
                    body?: string;
                    /** Format: uuid */
                    task_id?: string;
                };
            };
        };
        responses: {
            /** @description Created review */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewSummary"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Review */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewSummary"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listPlans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plan tree summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listCapability: {
        parameters: {
            query?: {
                action?: "list" | "missing";
                task_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Capability payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getImpact: {
        parameters: {
            query?: {
                task_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Impact report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listChanges: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Changes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listRegressions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Regressions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listAgents: {
        parameters: {
            query?: {
                action?: "list" | "recommend";
                task_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agents payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getIndexStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Index status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    postIndexReindex: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reindex accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    postAuthToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token issued (printed once; treat as secret) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token: string;
                        /** Format: date-time */
                        expires_at?: string | null;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    postBackup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            501: components["responses"]["Error"];
        };
    };
    postRestore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            501: components["responses"]["Error"];
        };
    };
    postMigrate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            501: components["responses"]["Error"];
        };
    };
    postInstall: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            501: components["responses"]["Error"];
        };
    };
    listPatterns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            501: components["responses"]["Error"];
        };
    };
    listKnowledge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            501: components["responses"]["Error"];
        };
    };
    getEval: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            501: components["responses"]["Error"];
        };
    };
    getEventsSSE: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            501: components["responses"]["Error"];
        };
    };
}
